### ISSUE TITLE
hindent moves comment and causes compile error

### ISSUE THREAD

**Issue by anacrolix** [commercialhaskell/hindent#498] opened 2018-05-11 09:37 UTC
Running hindent on this code:
```
module Network.Wai.Handler.Warp.Timeout (
  -- ** Types
  Manager
  , TimeoutAction
  , Handle
  -- ** Manager
```
results in
```
module Network.Wai.Handler.Warp.Timeout
  -- ** Types
  ( Manager
  , TimeoutAction
  , Handle
  -- ** Manager
```
Which causes the compile error
```
Network/Wai/Handler/Warp/Timeout.hs:5:3: error:
        parse error on input ‘-- ** Types’
      |
    5 |   -- ** Types
      |   ^^^^^^^^^^^
```

**Comment by chrisdone** [comment] 2018-07-08 22:34
Thanks, closing as duplicate of a previously submitted issue.

**Closed by chrisdone** 2018-07-08 22:34 UTC

**Comment by anacrolix** [comment] 2018-07-09 00:15
What's the other issue?

**Comment by chrisdone** [comment] 2018-07-09 08:32
I made a mega issue here: https://github.com/commercialhaskell/hindent/issues/511

It's all the same type of issue, that comments aren't associated with delimiter text (such as `where`, `(`, `[`, `=`, `let`, `do`, `,` etc.)
