### ISSUE TITLE
Hindent is not equipped to format Servant API Definitions

### ISSUE THREAD

**Issue by NorfairKing** [commercialhaskell/hindent#392] opened 2017-02-26 07:31 UTC
```
type UserAPI5
            = "user" :> Capture "userid" Integer :> Get '[JSON] User
           :<|> "user" :> Capture "userid" Integer :> DeleteNoContent '[JSON] NoContent
```

Gets reformatted to:

```
type UserAPI5 = "user" :> Capture "userid" Integer :> Get '[ JSON] User :<|> "user" :> Capture "userid" Integer :> DeleteNoContent '[ JSON] NoContent
```

**Comment by sighingnow** [comment] 2017-03-09 12:33
Hi, @NorfairKing, I'm not familiar with Servant API, but I'm sure that after format, the code can still pass compile. Could you provide any further explanation about the word "not euqipped" ?

**Comment by NorfairKing** [comment] 2017-03-09 12:53
Oh, this works, but it produces arbitrary-length lines.
The types for Servant API's become rather large.
This represents an API with only two endpoints, but your APi could have tens or hundreds.

**Comment by sighingnow** [comment] 2017-03-09 12:55
Thanks, I got it!

**Comment by NorfairKing** [comment] 2017-03-10 07:42
Ideally, we could split lines on `:<|>` but I'm not sure that we want to special-case this...

**Comment by tomsmalley** [comment] 2017-03-16 11:00
I tend to layout `:<|>` on newlines, so that would be okay for me.
But we also need to take into account when the individual routes exceed the line length limit.
Personally I like the style: 

```haskell
type GetUser = "user"
  :> Capture "userid" Integer
  :> Get '[JSON] User

type DeleteUser = "user"
  :> Capture "userid" Integer
  :> DeleteNoContent '[JSON] NoContent

type UserAPI = GetUser
          :<|> DeleteUser
```

Is there a way to preserve the given style? (newlines vs same line)

**Comment by NorfairKing** [comment] 2017-03-16 11:03
@tomsmalley +1 on this style, but I'm not sure whether this is possible without special-casing `:>` and/or `:<|>`

**Comment by sighingnow** [comment] 2017-03-16 11:20
The biggest concern of add special-rules for operators in some packages is that it may break pretty printing for ordinary programs, if they contain these operators.

A possible solution for this issue is adding a command line flag to enable special rules for these operator. But I'm wondering if it's a proper way for a pretty printer. Too many special cases would make hindent more unmaintainable.

**Comment by NorfairKing** [comment] 2017-03-16 11:24
@sighingnow Maybe we can break lines on every type operator in the same way?

**Comment by sighingnow** [comment] 2017-03-16 11:26
Sounds good. I will try this idea this weekend.

**Comment by shmish111** [comment] 2017-03-17 17:06
This is a real bugger, I had thought that hindent wouldn't remove newlines, rather only do indenting? Break on operator flag would be good though, so I can add config that says break on `:<|>`. If I hadn't found this issue we would probably have stopped using hindent :-(

**Comment by sighingnow** [comment] 2017-03-18 06:47
The difficulty of this issue lies in that HSE doesn't provide any information about the precedence about an infix operator. Thus breaking lines on every type operator is not a practical way @NorfairKing.

If we add `:<|>` to `line-breaks` configuration, we would get

~~~haskell
type UserAPI5
   = "user" :> Capture "userid" Integer :> Get '[ JSON] User
     :<|> "user" :> Capture "userid" Integer :> DeleteNoContent '[ JSON] NoContent
~~~

If we add `:>` and `:<|>` both to `line-breaks` configuration, we would get

~~~haskell
type UserAPI5
   = "user"
     :> Capture "userid" Integer
     :> Get '[ JSON] User
     :<|> "user"
     :> Capture "userid" Integer
     :> DeleteNoContent '[ JSON] NoContent
~~~

The result seems not good enough, but also not so bad. And for @tomsmalley's example, we would get

~~~haskell
type GetUser
   = "user"
     :> Capture "userid" Integer
     :> Get '[ JSON] User

type DeleteUser
   = "user"
     :> Capture "userid" Integer
     :> DeleteNoContent '[ JSON] NoContent

type UserAPI
   = GetUser
     :<|> DeleteUser
~~~

The seem rule could also be applied to infix operators on values, maybe related to issue #230.

How do you think about the layout result above? cc @NorfairKing @tomsmalley @shmish111

**Comment by NorfairKing** [comment] 2017-03-18 07:15
I'm happy with both options, but what happens to more common type operators? (I actually can't think of any examples). I wouldn't want to ruin other people's code formatting by this.

**Comment by NorfairKing** [comment] 2017-03-18 08:25
Hmm, I'm not sure how much I like that, and I'd like to hear other people's opinion on this matter.
I don't think configuration options are a good idea for hindent. It would be best if the output of hindent is completely deterministic and independent of any global state, but we already have `--indent-size` and `--line-length`, of course.

**Comment by tomsmalley** [comment] 2017-03-18 09:17
That looks reasonable to me.

**Comment by sighingnow** [comment] 2017-10-20 05:31
Closed as fixed.

**Closed by sighingnow** 2017-10-20 05:31 UTC
Labels: type: discussion

**Comment by NorfairKing** [comment] 2017-10-20 09:40
Is there a regression test for this?

**Comment by sighingnow** [comment] 2017-10-21 05:50
I haven't add the code I commented in [issuecomment-287521091](https://github.com/commercialhaskell/hindent/issues/392#issuecomment-287521091) to regression tests, due to the result code depends on the `line-break` operators in configuration file (or via command-line option). Currently I haven't found a proper way to add this case to `TEST.md` to setup a regression test.

**Comment by shmish111** [comment] 2018-10-16 14:02
Weirdly it seems that this works for the type operator but not for the value operator, so

```haskell
type MyAPI
  = API1
  :<|> API2
  :<|> API3

handlers = serve myAPI $
  api1 :<|> api2 :<|> api3
```

But I want and expected
```haskell
handlers = serve myAPI $
  api1 
  :<|> api2 
  :<|> api3
```
